### ISSUE TITLE
using System.Collections.Concurrent;

### ISSUE THREAD

**Issue by bflentje** [WFoundation/WF.Player.Core#11]
I've tried Visual Studio's 2012, 2013, and 2015, and cannot get access to the System.Collections.Concurrent assembly. It will not resolve. To be up front, I've never worked with a WindowsPhone project before. I get all references already added message.

**Comment by Mangatome** [comment]
The classes in System.Collections.Concurrent that the Core requires are missing from some platforms, e.g. Windows Phone 7/Silverlight. A compatible port of these classes is provided in the MonoClassLibraries of WFoundation/Eluant: https://github.com/WFoundation/Eluant/tree/master/MonoClassLibraries/System/Collections/Concurrent

A MonoClassLibraries-wp7 project is provided at https://github.com/WFoundation/Eluant/tree/master/MonoClassLibraries, but you might as well create a project for the platform you are targeting.

We aim at making the project PCL-compatible, therfore we will try to get rid of this dependency in the future.
